- title: Add API endpoint
  args:
    purpose: Purpose of the endpoint in the context of the PR Pilot API
    method: HTTP method to be used for the endpoint
    url: URL path for the endpoint
  instructions: |
    1. Create the new API endpoint in `api/views.py` and add the necessary logic to handle the request
    2. Add the new endpoint to `api/urls.py` to map the URL path to the view function
- title: Add new integration tool
  args:
    integration: Name of the integration for which to add a tool
    tool_name: Name of the tool
    description: Description of the integration tool and its purpose
    credentials_model: Name of the model used by the integration to store credentials
    implementation_details: Which lib/framework/API to use for the tool implementation, etc
  instructions: |
    0. Read `engine/agents/integration_tools/slack_tools.py` for reference on how to structure the tool 
    1. Find the right file for the integration in `engine/agents/integration_tools/` (create new one if necessary)
    2. Add the new tool to the integration file with the necessary methods and logic
    3. Register the new too in `engine/agents/integration_tools/__init__.py`
    4. Write the necessary tests for the new tool in the relevant file in `engine/agents/tests/`
- title: Add new integration setup page to dashboard
  args:
    integration: Name of the integration to add to the dashboard
    description: Description of the integration and its purpose
    auth_method: Authentication method used by the integration
    credentials_stored: List of credentials to be stored by the integration
  instructions: |
    1. Add a model for the credentials in `accounts/models.py` (if necessary) 
    2. If necessary, add a new tab for the integration in `dashboard/templates/integrations.html`
    3. Create a new template file in `dashboard/templates/integrations/` for the setup page (use the Slack one for reference)
    4. Add the necessary logic to `dashboard/views/integrations.py` to handle the new setup page