apiVersion: v2
name: pr-pilot
description: PR Pilot Helm Chart

type: application

version: 0.2.3

appVersion: "1.0.3"

dependencies:
  - name: redis
    version: "^10.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
