# Generated by Django 3.2 on 2024-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_slackintegration_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentryIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pilotuser',
            name='sentry_integration',
            field=models.OneToOneField(null=True, on_delete=models.CASCADE, to='accounts.sentryintegration'),
        ),
    ]
