apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-static
  template:
    metadata:
      labels:
        app: nginx-static
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.nginx }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-static-svc
spec:
  type: ClusterIP
  selector:
    app: nginx-static
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
