name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run tests
      run: tox

#    - name: Run tests
#      run: tox > tox_output.log 2>&1
#    - name: Analyze test results with PR Pilot
#      if: failure()
#      env:
#        PR_NUMBER: ${{ github.event.pull_request.number }}
#        PR_PILOT_API_KEY: ${{ secrets.PR_PILOT_API_KEY }}
#      run: |
#        pip install pr-pilot-cli==1.8.9
#        pilot --no-spinner task -f prompts/analyze_test_results.md.jinja2