name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.1
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox pr-pilot-cli
    - name: Run tests
      run: tox
    - name: Analyze test results with PR Pilot
      if: failure()
      env:
        PR_NUMBER: ${{ github.event.pull_request.number || 0 }}
      run: pilot -f prompts/analyze_test_results.md.jinja2