name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Debug information
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_PILOT_API_KEY: ${{ secrets.PR_PILOT_API_KEY }}
      run: |
        echo $PR_NUMBER
        echo {{ secrets.PR_PILOT_API_KEY }}

#    - name: Run tests
#      run: tox
#    - name: Analyze test results with PR Pilot
#      if: failure()
#      env:
#        PR_NUMBER: ${{ github.event.pull_request.number }}
#        PR_PILOT_API_KEY: ${{ secrets.PR_PILOT_API_KEY }}
#      run: |
#        pip install pr-pilot-cli==1.3.4
#        echo $PR_NUMBER