name: Update Task Engine Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'engine/task_*.py'

jobs:
  directory_change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List changed files
        run: |
          echo "Changed files in the specified directory:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'engine/' > changed_files.txt
          - name: Analyze test results with PR Pilot
      - env:
          PR_PILOT_API_KEY: ${{ secrets.PR_PILOT_API_KEY }}
        run: |
          pip install pr-pilot-cli==1.3.4
          pilot --raw -f prompts/update_engine_documentation.md.jinja2
