name: Update Task Engine Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'engine/task_*.py'

jobs:
  directory_change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - env:
          PR_PILOT_API_KEY: ${{ secrets.PR_PILOT_API_KEY }}
        run: |
          pip install pr-pilot-cli==1.4.1
          pilot --no-spinner --direct --model=gpt-4o -f prompts/task_processing_docs.md.jinja2 -o docs/code/task_processing.md
